# API e Dashboard
api:
  dashboard: true
  insecure: false

# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

# Entrypoints
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

# Certificate Resolvers
certificatesResolvers:
  tailscale:
    tailscale: {}

# Logging
log:
  level: INFO
  format: common

accessLog:
  format: common
